load("@rules_go//go:def.bzl", "go_library")

package(
    default_visibility = ["//visibility:public"]
)

go_library(
    name = "handlers",
    srcs = [
        "get_shortcut.go",
    ],
    importpath = "go-links/handlers",
)