load("@rules_go//go:def.bzl", "go_library")

package(
    default_visibility = ["//visibility:public"]
)

go_library(
    name = "middleware",
    srcs = ["middleware.go"],
    importpath = "go-links/middleware",
)