load("@rules_go//go:def.bzl", "go_library")

package(
    default_visibility = ["//visibility:public"]
)

go_library(
    name = "models",
    srcs = ["shortcut.go"],
    importpath = "go-links/models",
)